### ISSUE TITLE
Auth error after a while

### ISSUE THREAD

**Issue by TemoSulava** [aDarkDev/NotPixel#11]
So, the bot runs perfectly fine for an hour or so and then gives this error:
![image](https://github.com/user-attachments/assets/fa7c4714-1209-419c-a709-bbc4283eedad)

The steps i did were all according to the readme ( didn't read the actual code to look for the issue)

**Comment by Minecryp** [comment]
![Screenshot_20240925-120740_Termux](https://github.com/user-attachments/assets/613edc6a-2a1d-4451-9d73-aa8db260f713)
Same here.

**Comment by aDarkDev** [comment]
i will fix it in v1.6
