### ISSUE TITLE
ability to select a picture

### ISSUE THREAD

**Issue by tryxxje** [aDarkDev/NotPixel#2]
**Hello, I don’t know where to write to you, so I’m asking here, are you planning to add a function for loading a picture that the bot will draw?**

**Comment by aDarkDev** [comment]
It was a good idea, but it is difficult to make. The limit of 12 pixels also spoils the work. I will think about it in the future

**Comment by tryxxje** [comment]
> It was a good idea, but it is difficult to make. The limit of 12 pixels also spoils the work. I will think about it in the future

Well, I don’t know how difficult the implementation of this idea is, but the limitation can be bypassed by the number of accounts, let’s say I put sessions in the folder with or without jsons, I don’t know what would be better, well, in short, I threw in the sessions and the bot draws one picture from all sessions

**Comment by aDarkDev** [comment]
It is correct, in this case we also need multisession, if you are interested, you can participate. I will address this feature in the future
