### ISSUE TITLE
api id and hash error

### ISSUE THREAD

**Issue by AKa0258** [aDarkDev/NotPixel#29]
Sorry about this im not expert but i tried many bots like yescoin bot and get no error , im using same id and hash as yescoin bot but keep getting The api_id/api_hash combination is invalid (caused by SendCodeRequest). I try to fix it by myself with Chatgpt but i cant. Thx for help.

**Comment by aDarkDev** [comment]
generate your own api_id and api_hash from my.telegram.org > development

**Comment by AKa0258** [comment]
yes i did it but still getting this error. Can u help me pls
