### ISSUE TITLE
about proxy

### ISSUE THREAD

**Issue by boostrapz** [aDarkDev/NotPixel#32]
I read #6 
but NotPx.request is not available in search
![image](https://github.com/user-attachments/assets/7e5a5065-9a9c-4a24-b1f9-d9a1eb5a2dd1)

**Comment by boostrapz** [comment]
If possible please guide me through to implement proxies as I described in #27 
I really don't understand where do I hardcode proxy, and I don't want to hardcode, that's why I want to add proxy per session

**Comment by aDarkDev** [comment]
![image](https://github.com/user-attachments/assets/4f7b7334-7db9-4d53-8693-b611478aa847)
just put ur proxy like this.
