### ISSUE TITLE
run.bat

### ISSUE THREAD

**Issue by salehiparviz** [aDarkDev/NotPixel#34]
hi
i can not execute run.bat on ubuntu server is it possible to create run.sh for that

**Comment by aDarkDev** [comment]
just install libraries and run it simple with python3

**Comment by salehiparviz** [comment]
it is better than you create standard .sh file for ubuntu linux 
thanks

**Comment by aDarkDev** [comment]
linux installation:
pip3 install -r requirements.txt
python3 main.py 
🤷‍♂️
