### ISSUE TITLE
Альтернативный вход

### ISSUE THREAD

**Issue by HoyT6yK** [aDarkDev/NotPixel#39]
Недавно разработчики добавили легкий способ получения ссылки на вход в notpixel через браузер, рассматриваете ли добавление функции входа через нее?
![image_2024-09-27_11-58-12](https://github.com/user-attachments/assets/44d2ecc3-284d-4ead-a05d-e14670ee0445)

**Comment by aDarkDev** [comment]
Этот сайт имеет значение InitData, которое является вашим значением данных Telegram. Мой скрипт берет эти данные из Telethon
