### ISSUE TITLE
error

### ISSUE THREAD

**Issue by salehiparviz** [aDarkDev/NotPixel#51]
i think that it is better than to reopen program from running code and kill previous after 5 or 10 min for handling errors because time handling almost is impossible new error in below:

[!] 937 anti-detect: Sleeping for 3...
[!] 937: No charge available. Sleeping for 10 minutes...
[+] Authentication renewed!
[+] Authentication renewed!
[+] Authentication renewed!

**Comment by aDarkDev** [comment]
a7947c3847fb95f89424b338ee3ce0b007391c02
