### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by AliCybeRR** [aDarkDev/NotPixel#52]
+] Authentication renewed!
Server resent the older message 7419546691621292033, ignoring
[+] Authentication renewed!
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  149.154.167.92:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  149.154.175.58:443  ...  OK
[+] Authentication renewed!
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  149.154.167.92:443  ...  OK
[+] Authentication renewed!
[+] Authentication renewed!
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  149.154.167.92:443 [+] Authentication renewed!
[+] Authentication renewed!

**Comment by aDarkDev** [comment]
a7947c3847fb95f89424b338ee3ce0b007391c02
