### ISSUE TITLE
Drawing for the given design

### ISSUE THREAD

**Issue by mahdi429** [aDarkDev/NotPixel#55]
The paintPixel method is not used to paint the design, it is only painted randomly

**Comment by boostrapz** [comment]
there's nowhere said it'll paint by design

you can really change only x,y from where it'll start

**Comment by mahdi429** [comment]
> there's nowhere said it'll paint by design
> 
> you can really change only x,y from where it'll start

is it possible to paint it like a design?

**Comment by aDarkDev** [comment]
yes 

> > there's nowhere said it'll paint by design
> > you can really change only x,y from where it'll start
> 
> is it possible to paint it like a design?

yes use painPixel function

**Comment by mahdi429** [comment]
> yes
> 
> > > there's nowhere said it'll paint by design
> > > you can really change only x,y from where it'll start
> > 
> > 
> > is it possible to paint it like a design?
> 
> yes use painPixel function

How can I use it? Thank you for the guidance
