### ISSUE TITLE
"Sleeping in 1 hour" repeats after "Timeout Error".

### ISSUE THREAD

**Issue by mollyxs** [aDarkDev/NotPixel#57]
![IMG_2550](https://github.com/user-attachments/assets/e98c524f-7fac-41ad-9fcb-aacb0cce906c)

Everything seems to be working now, but when the script pauses for 1 hour, after a long period of inactivity a "timeout error" occurs, and when the connection is restored, the screen pauses again for 1 hour. The script doesn't paint pixels for almost 2 hours, but still the "claim" $PX works.

Ended up getting this error:
![image](https://github.com/user-attachments/assets/528ce340-4c13-4077-8c18-9d045169d09b)

**Comment by aDarkDev** [comment]
when you see your balance increase mean script works correctly,  because script gets balance from not pixel api. any questions?

**Comment by aDarkDev** [comment]
aha i got what you mean. i will add recursive function

**Comment by mollyxs** [comment]
> i will add recursive function

Thanks 😅👍

**Comment by dmitry-js** [comment]
Подтверждаю, скрипт отваливается после простоя
![Screenshot from 2024-09-28 16-07-38](https://github.com/user-attachments/assets/416b0b82-845d-4ffd-83eb-cd0600354a19)

**Comment by mollyxs** [comment]
> Подтверждаю, скрипт отваливается после простоя

У меня другая проблема, у меня то работает в принципе, но зацикливается андидетект на 1 час после ошибки таймаута, а то, что у тебя, у меня пофиксилось последним обновлением

**Comment by aDarkDev** [comment]
New Update Released.
