### ISSUE TITLE
THEY WANT STEAL UR ACCOUNT!!! DONT USE THIS

### ISSUE THREAD

**Issue by newbiehere10** [aDarkDev/NotPixel#62]
BOT OR SCRIPT NEVER ASK UR PHONE NUMBER AND TELEGRAM CODE..
BE CAREFULL OF SCAMMERS

YOU'RE IDIOT

**Comment by TemoSulava** [comment]
you are dumb lol

**Comment by TemoSulava** [comment]
> BOT OR SCRIPT NEVER ASK UR PHONE NUMBER AND TELEGRAM CODE.. BE CAREFULL OF SCAMMERS
> 
> YOU'RE IDIOT

are you dumb? :D

**Comment by salehiparviz** [comment]
Some people have sick thoughts
They provide the program code, you are just talking nonsense, where is this code stolen our data lier
If you are so ignorant about programming, don't use it
And lose your grave and go find it

**Comment by newbiehere10** [comment]
> Some people have sick thoughts
> They provide the program code, you are just talking nonsense, where is this code stolen our data lier
> If you are so ignorant about programming, don't use it
> And lose your grave and go find it

how many accounts do you have to comment on your own github and defend your main github account🤣.. they all know u are scammer🤣🤣.. how do i know? bcs i do samething idiot😅

**Comment by salehiparviz** [comment]
You are very stupid, I myself got a virtual number and two real numbers banned
Of course, because of my mistake, you can see it in the previous comments
But in general you are very stupid

**Comment by newbiehere10** [comment]
> You are very stupid, I myself got a virtual number and two real numbers banned
> Of course, because of my mistake, you can see it in the previous comments
> But in general you are very stupid

me? stupid🤣🤣 hey idiot. u want to steal our main account🤣. is there a bot script that asks for phone numbers and login OTP? if not your script is weird hhh.. I made a not pixel script just using query_id. i never ask for phone numbers and their otp🤣.. 

U ARE IDIOT SCAMMER I HOPE U WILL DIE BY SOMEONE ARMED AND SHOOT UR HEAD

**Comment by aDarkDev** [comment]
> > You are very stupid, I myself got a virtual number and two real numbers banned
> > Of course, because of my mistake, you can see it in the previous comments
> > But in general you are very stupid
> 
> me? stupid🤣🤣 hey idiot. u want to steal our main account🤣. is there a bot script that asks for phone numbers and login OTP? if not your script is weird hhh.. I made a not pixel script just using query_id. i never ask for phone numbers and their otp🤣..
> 
> U ARE IDIOT SCAMMER I HOPE U WILL DIE BY SOMEONE ARMED AND SHOOT UR HEAD

i never see clown like you
