### ISSUE TITLE
Api, hash и proxy в отдельный файл

### ISSUE THREAD

**Issue by mollyxs** [aDarkDev/NotPixel#63]
Можно ли вынести эти параметры в отдельный файл? То после каждого обновления приходится лезть в main.py и прописывать заново api и hash. Неудобно как будто. И если есть возможность прикрутить прокси в отдельный файл. То если мультиачить и после каждого обновления закидывать в каждую папку main.py и в каждом этом файле на каждом аккаунте прописывать заново эти параметры — это ад. А так просто раскидал main.py по папкам в каждый аккаунт и забыл

**Comment by aDarkDev** [comment]
Я обязательно это сделаю спасибо

**Comment by mollyxs** [comment]
> Я обязательно это сделаю спасибо

Будет здорово, спасибо 🌝👍

**Comment by aDarkDev** [comment]
Выпущено новое обновление.
