### ISSUE TITLE
Пояснение по обновлению 😅

### ISSUE THREAD

**Issue by mollyxs** [aDarkDev/NotPixel#64]
После запуска сессии в консоли сразу отображает это:

![IMG_2566](https://github.com/user-attachments/assets/e46c983d-1c13-4967-9682-bf604010a8b0)

Связано ли это с тем, что в конфиге я указал уровни прокачки выше, чем те которые у меня есть на данный момент?

А так работает, только непонятно почему сразу после запуска на час в антидетект уходит 🌚

И кстати, было бы неплохо к каждому новому действию в консоли добавить время, например тот же антидетект когда уходит на час, чтобы было видно во сколько по времени начался простой и чтобы понимать во сколько он завершится. Да и в целом удобно кажется это. Если не сложно 🌝🙏

**Comment by aDarkDev** [comment]
36f16783689f08ea78f22efa81add7a95780db8b

**Comment by aDarkDev** [comment]
Подсчет того, сколько времени прошло за 1 час, делает код немного перегруженным.

**Comment by aDarkDev** [comment]
А также этот максимум соответствует уровню, который вы хотите повысить.

**Comment by mollyxs** [comment]
Понял, спасибо. А можно например вынести в config.py параметр юзерагента? Чтобы для разных акков можно было свой какой-то указать

**Comment by boostrapz** [comment]
> Подсчет того, сколько времени прошло за 1 час, делает код немного перегруженным.

dumayu on imel vvidy timestamp sleva chtobi bilo vremya [hh:mm:ss] kajdogo deistviya, a ne taimer skolko ostalos do konca sna (sorry za translit, raskladki nety)

**Comment by boostrapz** [comment]
I esli mojno dobav' ewe parser chtobi procheckat' kakie lvla boostov na akkax
