### ISSUE TITLE
don't buy upgrades

### ISSUE THREAD

**Issue by ParsapythonLv** [aDarkDev/NotPixel#79]
just painting and claim , don't buy any boosts

**Comment by aDarkDev** [comment]
yes its useless, It has no effect

**Comment by boostrapz** [comment]
> yes its useless, It has no effect

wdym, energy limit I agree, useless. 
Restore charge OP, less time to get 1nrg, and PX per coloring good after fast recharge

btw, not paintin as of now and the script never bought boosts itself
