### ISSUE TITLE
Can you tell me how you extract api from mini web app if it only open in mobile? 

### ISSUE THREAD

**Issue by viki-ramesh** [aDarkDev/NotPixel#8]
Hello sir, I'm learning so that's why i asked that stupid question. If you can answers it wil help me on learning.

**Comment by aDarkDev** [comment]
Hello, no, it's good to help. There is a function in my code called GetQuery... you can get the full link as msg.url from telegram and extract it in "burp suit" or "chrome". If you don't even know simple sniffing, search Google "intercept network chrome"

**Comment by viki-ramesh** [comment]
Thank you very much sir
