### ISSUE TITLE
Termux

### ISSUE THREAD

**Issue by IMPER1A-V** [aDarkDev/NotPixel#85]
Пытался переписать run .bat на sh для termux, но выдает permission denied. Видимо не удается у меня создать виртуальную среду. Мог бы автор помочь с этим ?

**Comment by aDarkDev** [comment]
почему вы хотите сделать env?

**Comment by IMPER1A-V** [comment]
> почему вы хотите сделать env?

Если я правильно понял ,то файл run.bat создаёт виртуальную среду и после запускает main.py. хотел это и реализовать для termux

**Comment by aDarkDev** [comment]
для Linux-систем, таких как termux, его не нужно запускать в виртуальной среде, потому что нужно установить и запустить только 2 библиотеки! это очень просто. наконец-то я не работал с termux
