### ISSUE TITLE
Вряд-ли , возможно проблема со входом

### ISSUE THREAD

**Issue by salehiparviz** [aDarkDev/NotPixel#95]
Вряд-ли , возможно проблема со входом

_Originally posted by @IMPER1A-V in https://github.com/aDarkDev/NotPixel/issues/94#issuecomment-2395069201_
            translate: 1 Pixel painted successfully. User new balance: 5140
[!] translate anti-detect: Sleeping for 1...
[+] translate: 1 Pixel painted successfully. User new balance: 5140
[!] translate anti-detect: Sleeping for 2...
[+] translate: 1 Pixel painted successfully. User new balance: 5140
[!] translate anti-detect: Sleeping for 2...
[+] Auto claiming started.
[+] translate: 0.34 NotPx Token claimed.
[!] translate: Sleeping for 1 hour...
[+] translate: 1 Pixel painted successfully. User new balance: 5140
[!] translate anti-detect: Sleeping for 3...
[+] translate: 1 Pixel painted successfully. User new balance: 5140
[!] translate anti-detect: Sleeping for 5...
[+] translate: 1 Pixel painted successfully. User new balance: 5140
[!] translate anti-detect: Sleeping for 4...

**Comment by salehiparviz** [comment]
I think it ban me

**Comment by aDarkDev** [comment]
u run that 24h?

**Comment by salehiparviz** [comment]
yes i run that 24h

**Comment by salehiparviz** [comment]
> u run that 24h?

yes

**Comment by krishealty** [comment]
how can i run it for 24hour?

**Comment by aDarkDev** [comment]
https://github.com/aDarkDev/NotPixel/blob/18d06cae85a6f0d6aa3c1c4d5d5d2a6a4d434d56/main.py#L370
> > u run that 24h?
> 
> yes
